读取配置信息问题
php-casbin/think-authz pull request #39
Opened 2022-06-02 06:11 UTC by zhangyue0503

读取配置信息键名有问题

不过读对了也没用，think-migration 有问题，已经向那边提交了 issue [数据库迁移脚本向不同的连接库迁移问题](https://github.com/top-think/think-migration/issues/70)

2022-06-02 06:24 UTC, hsluoyz commented
@leeqvip

2022-06-10 02:11 UTC, leeqvip requested changes

2022-06-10 02:11 UTC, leeqvip commented on database/migrations/20181113071924_create_rules_table.php
First you should get the default `enforcer`, and then get the `database.connection` in it.
```php
$default =config('tauthz.default');
$connection= config("tauthz.enforcers.{$default}.database.connection") ?: config('database.default');

$config = config("database.connections.{$connection}");
```

2022-06-10 02:29 UTC, zhangyue0503 commented on database/migrations/20181113071924_create_rules_table.php
没毛病

2022-06-10 02:35 UTC, zhangyue0503 reviewed
没毛病，还是要走配置文件，我给直接写死了

2022-06-10 15:20 UTC, leeqvip commented
> 没毛病，还是要走配置文件，我给直接写死了
@zhangyue0503 You seem to have forgotten to modify the last line of code.

2022-06-11 15:44 UTC, leeqvip approved these changes

2022-06-11 15:54 UTC, merged

2022-06-11 15:56 UTC, leeqvip commented
:tada: This PR is included in version 1.5.4 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/think-authz/releases/tag/v1.5.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: