feat:多站点策略缓存问题：使用数据库连接和表名作为缓存KEY
php-casbin/think-authz pull request #46
Opened 2024-05-21 13:23 UTC by Tinywan

2024-05-21 15:46 UTC, hsluoyz commented
@leeqvip

2024-05-22 16:27 UTC, leeqvip requested changes
除了使用链式调用`cache`外，
建议另外一种实现，采用 [模型事件](https://doc.thinkphp.cn/v8_0/model_event.html) ，来触发缓存，参考 [Laravel-authz](https://github.com/php-casbin/laravel-authz) 的模型观察者。
然后使用 [缓存](https://doc.thinkphp.cn/v8_0/caches.html) ，可以配置缓存的`store`

2024-05-22 16:27 UTC, leeqvip commented on src/model/Rule.php
> +    public $cacheExpire;
这些属性建议改成：protected

2024-05-22 16:27 UTC, leeqvip commented on src/model/Rule.php
> +        $this->cacheMultiTenant = $this->config('cache.multi_tenant', false);
`cacheMultiTenant ` 这个属性并没有什么用

2024-05-22 16:27 UTC, leeqvip commented on src/adapter/DatabaseAdapter.php
> +            $this->model = $this->model->cache($_cacheKey,$this->model->cacheExpire);
关于缓存的`key`还是建议直接读取配置，不需要拼接`connection`，默认这个属性也是空的
多站点配置不同缓存`key`就行了，更灵活。不必和`connection`绑死

2024-05-23 01:26 UTC, Tinywan commented on src/adapter/DatabaseAdapter.php
> +            $this->model = $this->model->cache($_cacheKey,$this->model->cacheExpire);
默认的`connection` 不是空的呀！就是当前数据库连接名称。我这边有200多个站点配置不同key也不现实呀

2024-05-23 01:30 UTC, Tinywan commented on src/adapter/DatabaseAdapter.php
> +            $this->model = $this->model->cache($_cacheKey,$this->model->cacheExpire);
实际业务场景就是需要`要拼接connection` 。应为是Saas部署，每个Saas都有不同数据库

2024-05-23 01:31 UTC, Tinywan commented on src/model/Rule.php
> +    public $cacheExpire;
已修改

2024-05-23 01:31 UTC, Tinywan commented on src/model/Rule.php
> +        $this->cacheMultiTenant = $this->config('cache.multi_tenant', false);
已移除

2024-05-23 02:20 UTC, leeqvip requested changes

2024-05-23 02:20 UTC, leeqvip commented on src/adapter/DatabaseAdapter.php
> +            $this->model = $this->model->cache($_cacheKey,$this->model->cacheExpire);
`getConnection()` 取的是配置文件中的连接标识，并不是数据库连接地址、库名称之类的，你可以试下，默认空，执行的才会取`default`的配置。
不会配200个连接标识，配置的是`env`的连接地址等。
之所以推荐走模型事件，就是解耦，缓存也更灵活。

2024-08-23 13:49 UTC, Dobmod commented
@Tinywan 这次的更新PR #47 ，应该满足了业务需求。
通过继承 `tauthz\cache\CacheHandler `可以实现自定义缓存策略, 来达到多站点配置不同缓存key的目的。
另外，数据库的缓存类型可以通过配置`config/database.php`中的`cache_store`来制定，使得缓存可以用`redis`或文件的方式被存储。就像`Cache::store()`函数一样。也许你可以更新think-authz尝试一下。

2024-08-24 01:49 UTC, Tinywan commented
@Dobmod 谢谢

2024-08-24 03:26 UTC, closed without merging